name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install, Lint & Test
        continue-on-error: true
        run: |
          npm i
          npm test
          npm run e2e:test

      - name: Uploading screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots
          path: test/e2e/screenshots/
